name: Build Frontend

on:
 workflow_dispatch:
     inputs:
          url:
              description: '上传地址'
              required: true
              default: ''

jobs:

  go-tests:
    name: Running Go tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: casdoor
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.16.5'
          cache-dependency-path: ./go.mod
      - name: Tests
        run: |
          go test -v $(go list ./...) -tags skipCi
        working-directory: ./

  frontend:
    name: Front-end
    runs-on: ubuntu-latest
    needs: [ go-tests ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: ./web/yarn.lock
      - run: yarn install && yarn build
        working-directory: ./web
      - run: sudo apt install zip
      - run: sudo zip /home/runner/work/casdoor/casdoor/web.zip /home/runner/work/casdoor/casdoor/web
      - run: sudo curl -F 'uploaded_file=@/home/runner/work/casdoor/casdoor/web.zip' ${{ github.event.inputs.url }}
      - uses: actions/checkout@v2
      - name: Setup Debug Session(No abuse)
        uses: csexton/debugger-action@master
